# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'ZyncExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage'
  pod 'lottie-ios'

  target 'ZyncExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZyncExampleUITests' do
    # Pods for testing
  end

end
